### ISSUE TITLE
The tag different with crypto implement

### ISSUE THREAD

**Issue by yanjh007** [aydon14/Chacha20-Poly1305-in-Javascript#1]
Just run the test function, you will see:

  PS C:\Work\Dev\cauth\test> node c1.js          
  Ciphertext: cb6f8ecd75384b5af99ae31900592860ae7c5ac12f864b
  Tag: f53e7da55d06250e49ef0016b3313964
  Ciphertext (crypto): cb6f8ecd75384b5af99ae31900592860ae7c5ac12f864b
  Tag (crypto): f53e7da5fd931229f125f0e23ea9462b
  Decrypted plaintext: This is a test message.

So, the encrypt is OK, but note the tag is not same!! I write a check code use crypto to decrypt the content and use the tag, it's false. 

So Is there some problem?? Pls check and give a feedback, thanks!! 
yan.jianhua@gmail.com

**Comment by aydon14** [comment]
Hi there!

Thanks for pointing this out to me. The issue was due to mishandling the key for the tag calculation. To solve the issue, the key is now read in little-endian order when calculating the tag. I have also updated the test function to include a variety of tests for better accuracy. The issue should now be fixed in the newest release.

Best regards, Aydon.

**Comment by yanjh007** [comment]
OK, Thanks Very much
By the way， I modify a pure js version of chacha-1305 based on your version，remove the Buffer depend, and works in cloudflare worker or browser,  pls check it out if you interesting.  

https://github.com/yanjh007/somecool/blob/main/chacha20-poly1305.js
